### ISSUE TITLE
git urls dont work when installing a builder component

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/builder-victory-component#32] opened 2016-01-27 06:55 UTC
repro: in a victory component, change the version of one of the dependent victory components so that it points to a git url. `npm install` should result in the following error:

```
Error: Cannot find module '/Users/boygirl/formidable/v/victory-bar/node_modules/victory-label/node_modules/builder-victory-component/config/webpack/webpack.config.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (/Users/boygirl/formidable/v/victory-bar/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/boygirl/formidable/v/victory-bar/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

I know there was discussion around this `node_module` flattening, issue, but is there a resolution yet? The above repro was seen with most recent versions of builder and victory archetype dependencies in both the child and consuming victory repos.

**Comment by ryan-roemer** [comment] 2016-01-27 14:56
Duplicate of https://github.com/FormidableLabs/builder-victory-component/issues/23

**Closed as completed by ryan-roemer** 2016-01-27 14:56 UTC
Labels: duplicate
